name: issue created or edited
on:
  issues:
    types: [opened, edited, reopened, labeled, unlabeled]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: cat ${GITHUB_EVENT_PATH}
      - name: checkout
        uses: actions/checkout@v2.3.1
      - name: install dependencies
        run: pip3 install bleach
      - name: Set env
        id: set-env
        run: |
          echo "FILE_NAME=_posts/$(cat ${GITHUB_EVENT_PATH} | jq -r '.issue.created_at' | sed 's/T.*$//g')-$(cat ${GITHUB_EVENT_PATH} | jq -r '.issue.number').md" >> "$GITHUB_OUTPUT"
          echo "PAGE_TITLE=$(cat ${GITHUB_EVENT_PATH} | jq -r '.issue.title')" >> "$GITHUB_OUTPUT"
          echo "PAGE_DATE=$(cat ${GITHUB_EVENT_PATH} | jq -r '.issue.created_at' | sed 's/T/ /g' | sed 's/Z$//g')" >> "$GITHUB_OUTPUT"
          echo "PAGE_TAGS=$(cat ${GITHUB_EVENT_PATH} | jq -r '.issue.labels[].name' | xargs)" >> "$GITHUB_OUTPUT"
      - name: Generate content
        run: |
          cat ${GITHUB_EVENT_PATH} | jq -r '.issue.body' | python3 -c 'import bleach, sys; sys.stdout.write(bleach.clean(sys.stdin.read()))' > ${{steps.set-env.outputs.FILE_NAME}}
          sed -i '1i ---' ${steps.set-env.outputs.FILE_NAME}
          sed -i '1i tags: '"${{steps.set-env.outputs.PAGE_TAGS}}"'' ${{steps.set-env.outputs.FILE_NAME}}
          sed -i '1i date: '"${{steps.set-env.outputs.PAGE_DATE}}"'' ${{steps.set-env.outputs.FILE_NAME}}
          sed -i '1i title: '"${{steps.set-env.outputs.PAGE_TITLE}}"'' ${{steps.set-env.outputs.FILE_NAME}}
          sed -i '1i ---' ${{steps.set-env.outputs.FILE_NAME}}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{steps.set-env.outputs.FILE_NAME}}
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
